# Generated by Django 3.2.8 on 2021-11-10 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211107_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicsubscription',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comicsubscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comicsubscription',
            name='rating',
        ),
    ]
