# Generated by Django 3.2.8 on 2021-12-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_readissue_watched_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readissue',
            old_name='watched_at',
            new_name='read_at',
        ),
    ]
