# Generated by Django 3.2.7 on 2021-12-24 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211220_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonsubscription',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
