# Generated by Django 4.0 on 2021-12-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0023_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikedThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'unique_together': {('user', 'thought')},
            },
        ),
    ]
