# Generated by Django 3.2.7 on 2022-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_imagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
