# Generated by Django 3.2.7 on 2022-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_imagerequest_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='status',
            field=models.CharField(choices=[('NONE', 'None'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NONE', max_length=50),
        ),
    ]
