# Generated by Django 3.2.7 on 2022-01-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_auto_20220113_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('comics_Publisher', 'comic_publisher'), ('comics_Staff', 'comic_staff'), ('comics_Character', 'comic_character'), ('comics_Comic', 'comic_comic'), ('comics_Issue', 'comic_issue'), ('cartoons_VoiceActor', 'cartoon_voiceactor'), ('cartoons_Network', 'cartoon_network'), ('cartoons_Character', 'cartoon_character'), ('cartoons_Cartoon', 'cartoon_series'), ('cartoons_Episode', 'cartoon_episode')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NONE', 'None'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NONE', max_length=50)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
