# Generated by Django 3.2.7 on 2022-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220202_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='object_type',
            field=models.CharField(choices=[('comics_Publisher', 'comic_publisher'), ('comics_Staff', 'comic_staff'), ('comics_Comic', 'comic_comic'), ('comics_Issue', 'comic_issue'), ('cartoons_VoiceActor', 'cartoon_voiceactor'), ('cartoons_Network', 'cartoon_network'), ('cartoons_Character', 'cartoon_character'), ('cartoons_Cartoon', 'cartoon_series'), ('cartoons_Episode', 'cartoon_episode'), ('cartoons_Team', 'cartoon_team')], max_length=50),
        ),
    ]
