# Generated by Django 3.2.7 on 2022-02-21 19:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[users.models.UserData.validate_char]),
        ),
    ]
