# Generated by Django 3.2.7 on 2022-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20220226_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='object_type',
            field=models.CharField(choices=[('comics_Publisher', 'comic_publisher'), ('comics_Staff', 'comic_staff'), ('comics_Comic', 'comic_comic'), ('comics_Issue', 'comic_issue'), ('cartoons_VoiceActor', 'cartoon_voiceactor'), ('cartoons_Network', 'cartoon_network'), ('cartoons_Character', 'cartoon_character'), ('cartoons_Cartoon', 'cartoon_series'), ('cartoons_Episode', 'cartoon_episode'), ('cartoons_Team', 'cartoon_team'), ('cartoons_Location', 'cartoon_location'), ('users_Thought', 'users_thought'), ('users_Comment', 'users_comment'), ('users_Comment', 'users_comment'), ('auth_User', 'auth_user')], max_length=50),
        ),
    ]
