# Generated by Django 3.2.8 on 2021-11-02 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=10000)),
                ('season_count', models.IntegerField(default=1)),
                ('image_small', models.URLField(blank=True)),
                ('image_medium', models.URLField(blank=True)),
                ('image_large', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('absolute_episode_number', models.IntegerField()),
                ('season_number', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('screenshot', models.URLField(blank=True)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoons.cartoon')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True)),
                ('voice_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoons.voiceactor')),
            ],
        ),
        migrations.AddField(
            model_name='cartoon',
            name='genres',
            field=models.ManyToManyField(blank=True, to='cartoons.Genre'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoons.network'),
        ),
    ]
