# Generated by Django 3.2.8 on 2021-12-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0002_auto_20211102_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartoons.series'),
            preserve_default=False,
        ),
    ]
