# Generated by Django 3.2.7 on 2021-12-23 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0009_auto_20211223_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartoons.series'),
        ),
        migrations.AlterField(
            model_name='character',
            name='voice_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartoons.voiceactor'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
