# Generated by Django 3.2.7 on 2021-12-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0012_alter_series_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
