# Generated by Django 4.0 on 2021-12-25 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0016_alter_cartoon_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
