# Generated by Django 3.2.7 on 2022-02-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0028_episode_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceactor',
            name='age',
        ),
    ]
