# Generated by Django 3.2.7 on 2022-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0029_remove_voiceactor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('RELEASING', 'Releasing'), ('PLANNED', 'Planned'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
