# Generated by Django 3.2.7 on 2022-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0030_alter_cartoon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
