# Generated by Django 3.2.7 on 2022-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0033_alter_character_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(choices=[('ANTI-HERO', 'Anti-Hero'), ('GOOD', 'Good'), ('EVIL', 'Evil')], default='GOOD', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], default='ALIVE', max_length=100),
        ),
    ]
