# Generated by Django 3.2.7 on 2022-02-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0036_character_base_of_operations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='base_of_operations',
            new_name='location_of_operation',
        ),
    ]
