# Generated by Django 3.2.7 on 2022-02-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0037_rename_base_of_operations_character_location_of_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='base_name',
        ),
    ]
