# Generated by Django 3.2.7 on 2022-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0039_auto_20220221_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='disbanded_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='disbanded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
