# Generated by Django 3.2.8 on 2021-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_name',
            field=models.CharField(default='Rick and Morty: Pocket Like You Stole It #1', max_length=250),
            preserve_default=False,
        ),
    ]
