# Generated by Django 3.2.8 on 2021-10-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_issue_issue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_name',
        ),
    ]
