# Generated by Django 3.2.8 on 2021-10-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_remove_issue_issue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('WRITER', 'Writer'), ('PENCILLER', 'Penciller'), ('COVER ARTIST', 'Cover Artist'), ('INKER', 'Inker'), ('VARIANT COVER ARTIST', 'Variant Cover Artist'), ('COLORIST', 'Colorist'), ('LETTERER', 'Letterer'), ('DESIGNER', 'Designer'), ('EDITOR', 'Editor'), ('EXECUTIVE EDITOR', 'Executive Editor'), ('EDITOR-IN-CHIEF', 'Editor-in-Chief')], max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='image_large',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='image_medium',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='image_small',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='image_large',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='image_medium',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='image_small',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='characters',
            field=models.ManyToManyField(to='comics.Character'),
        ),
        migrations.AddField(
            model_name='series',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comics.publisher'),
            preserve_default=False,
        ),
    ]
