# Generated by Django 3.2.8 on 2021-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20211027_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='characters',
        ),
        migrations.AddField(
            model_name='issue',
            name='characters',
            field=models.ManyToManyField(to='comics.Character'),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
