# Generated by Django 3.2.8 on 2021-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_auto_20211028_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='staff',
            field=models.ManyToManyField(to='comics.Staff'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
