# Generated by Django 3.2.8 on 2021-11-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0015_auto_20211107_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('issue_number_absolute', 'series')},
        ),
    ]
