# Generated by Django 3.2.7 on 2021-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0020_auto_20211222_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.URLField(blank=True, default='test'),
            preserve_default=False,
        ),
    ]
