# Generated by Django 3.2.7 on 2021-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0025_auto_20211222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('RELEASING', 'Releasing'), ('PLANNED', 'Planned')], default='fsdf', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatusOptions',
        ),
    ]
