# Generated by Django 3.2.7 on 2021-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0026_auto_20211222_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
