# Generated by Django 3.2.7 on 2021-12-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0029_character_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.publisher'),
        ),
    ]
