# Generated by Django 3.2.8 on 2022-01-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0036_alter_comic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
