# Generated by Django 3.2.7 on 2022-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0038_auto_20220111_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
