# Generated by Django 3.2.7 on 2022-02-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0026_character_alias'),
        ('comics', '0041_auto_20220112_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AlterField(
            model_name='issue',
            name='characters',
            field=models.ManyToManyField(blank=True, to='cartoons.Character'),
        ),
    ]
