# Generated by Django 3.2.7 on 2022-02-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0042_auto_20220201_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
    ]
