# Generated by Django 3.2.7 on 2022-02-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0045_alter_issue_issue_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_number',
            new_name='issue_name',
        ),
    ]
