# Generated by Django 3.2.7 on 2022-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0046_rename_issue_number_issue_issue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_name',
            field=models.CharField(max_length=200),
        ),
    ]
