# Generated by Django 3.2.8 on 2021-11-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userbio_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBio',
        ),
    ]
