# Generated by Django 3.2.8 on 2021-11-05 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_alter_issue_issue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_comicsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comicsubscription',
            unique_together={('series', 'user')},
        ),
    ]
