# Generated by Django 3.2.8 on 2021-11-10 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0018_auto_20211107_1428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20211110_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicsubscription',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterUniqueTogether(
            name='comicsubscription',
            unique_together={('series', 'user')},
        ),
        migrations.RemoveField(
            model_name='comicsubscription',
            name='watched_at',
        ),
    ]
