# Generated by Django 3.2.8 on 2021-12-18 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0003_character_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_cartoonsubscription_watchedcartoon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedCartoon',
            new_name='WatchedEpisode',
        ),
    ]
