# Generated by Django 3.2.7 on 2021-12-20 10:04

from django.db import migrations

THOUGHT_TYPES = [
    {
        'name': 'COMIC'
    },
    {
        'name': 'ISSUE'
    },
    {
        'name': 'CARTOON'
    },
    {
        'name': 'EPISODE'
    },
]

# This function adds all the initial predefined Sectors
def add_types(apps, schema_editor):
    ThoughtType = apps.get_model('users', 'ThoughtType')

    for type in THOUGHT_TYPES:
        ThoughtType.objects.get_or_create(
            name = type['name']
        )


def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_comment_thought_thoughttype'),
    ]

    operations = [
        migrations.RunPython(add_types, reverse)
    ]
