# Generated by Django 4.0 on 2021-12-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_thought_cartoon_remove_thought_comic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='related_object',
            new_name='related_object_id',
        ),
    ]
