# Generated by Django 4.0 on 2021-12-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_related_object_thought_related_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
