# Generated by Django 3.2.8 on 2021-12-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userlikedthought'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThoughtType',
        ),
    ]
