# Generated by Django 3.2.7 on 2022-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_imagerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='object_type',
            field=models.CharField(choices=[('comics_Publisher', 'comic_publisher'), ('comics_Staff', 'comic_staff'), ('comics_Character', 'comic_character'), ('comics_Comic', 'comic_comic'), ('comics_Issue', 'comic_issue'), ('cartoons_VoiceActor', 'cartoon_voiceactor'), ('cartoons_Network', 'cartoon_network'), ('cartoons_Character', 'cartoon_character'), ('cartoons_Cartoon', 'cartoon_series'), ('cartoons_Episode', 'cartoon_episode')], max_length=50),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='request_field',
            field=models.CharField(choices=[('COVER', 'Cover'), ('BACKGROUND', 'Background'), ('GENERIC', 'Generic'), ('LOGO', 'Logo'), ('SCREENSHOT', 'Screenshot')], max_length=50),
        ),
    ]
