# Generated by Django 3.2.8 on 2021-10-28 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20211028_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='year_started',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
