# Generated by Django 3.2.8 on 2021-10-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_auto_20211030_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_number_absolute',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.CharField(max_length=50),
        ),
    ]
