# Generated by Django 3.2.8 on 2021-11-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_auto_20211107_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='absolute_issue_number',
            new_name='issue_number_absolute',
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('issue_number_absolute', 'series')},
        ),
    ]
