# Generated by Django 3.2.7 on 2021-12-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0019_auto_20211220_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='image_large',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='image_large',
            new_name='background_image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_medium',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_small',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image_medium',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image_small',
        ),
        migrations.AddField(
            model_name='series',
            name='cover_image',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
