# Generated by Django 3.2.7 on 2021-12-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0021_auto_20211222_1615'),
    ]

    operations = [
    ]
