# Generated by Django 3.2.7 on 2021-12-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0022_auto_20211222_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.staffpositions'),
        ),
    ]
