# Generated by Django 3.2.7 on 2021-12-22 16:45

from django.db import migrations

STAFF_POSITIONS = [
    {
        'position': 'Writer'
    },
    {
        'position': 'Penciller'
    },
    {
        'position': 'Cover Artist'
    },
    {
        'position': 'Inker'
    },
    {
        'position': 'Variant Cover Artist'
    },
    {
        'position': 'Colorist'
    },
    {
        'position': 'Letterer'
    },
    {
        'position': 'Designer'
    },
    {
        'position': 'Editor'
    },
    {
        'position': 'Executive Editor'
    },
    {
        'position': 'Editor-in-Chief'
    },
]

def addPositions(apps, schema_editor):
    StaffPositions = apps.get_model('comics', 'StaffPositions')
    print(StaffPositions)
    for pos in STAFF_POSITIONS:
        position = pos['position']
        StaffPositions.objects.get_or_create(
            position = pos['position']
        )

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0023_auto_20211222_1723'),
    ]

    operations = [
        migrations.RunPython(addPositions, reverse)
    ]
