# Generated by Django 3.2.7 on 2021-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0027_auto_20211223_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
