# Generated by Django 3.2.7 on 2021-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0028_auto_20211223_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
