# Generated by Django 4.0 on 2021-12-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_cartoonsubscription_rating'),
        ('comics', '0033_alter_staff_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Comic',
        ),
    ]
