# Generated by Django 3.2.7 on 2022-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0040_auto_20220112_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comic',
            name='background_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comic',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
