# Generated by Django 3.2.7 on 2022-02-24 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('thought_type', models.CharField(blank=True, choices=[('COMIC', 'Comic'), ('ISSUE', 'Issue'), ('CARTOON', 'Cartoon'), ('EPISODE', 'Episode')], max_length=10, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikedThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'thought')},
            },
        ),
    ]
