# Generated by Django 3.2.7 on 2022-02-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='num_of_likes',
        ),
        migrations.DeleteModel(
            name='UserLikedThought',
        ),
    ]
