# Generated by Django 3.2.7 on 2021-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0003_character_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image_medium',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image_small',
        ),
        migrations.AddField(
            model_name='series',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
