# Generated by Django 3.2.7 on 2021-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0006_auto_20211223_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
