# Generated by Django 3.2.7 on 2021-12-24 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0010_auto_20211223_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='rating',
        ),
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
