# Generated by Django 4.0 on 2021-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0013_voiceactor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='characters',
            field=models.ManyToManyField(blank=True, to='cartoons.Character'),
        ),
    ]
