# Generated by Django 3.2.8 on 2022-01-01 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0017_alter_cartoon_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
