# Generated by Django 3.2.8 on 2022-01-01 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0018_cartoon_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='episode',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='network',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
