# Generated by Django 3.2.8 on 2022-01-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0020_alter_episode_release_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('episode_number', 'season_number', 'series')},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='absolute_episode_number',
        ),
    ]
