# Generated by Django 3.2.8 on 2022-01-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0021_auto_20220101_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
