# Generated by Django 3.2.7 on 2022-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0024_auto_20220112_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='background_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='screenshot',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='network',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='voiceactor',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
